apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    url: timescaledb:5432
    user: sensor
    secureJsonData:
      password: sensor
    jsonData:
      database: sensordb
      sslmode: disable
      timescaledb: true
